# Generated by Django 5.2.6 on 2025-09-09 09:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image_caption', 3), ('quote', 5), ('statistic', 7), ('cta', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'ol', 'ul', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('number', 6), ('label', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-blue-500', 'Blue'), ('bg-green-500', 'Green')], 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 4), ('button_link', 8), ('background_color', 9)]], {})}, null=True),
        ),
    ]
